model:
  _target_: get_model.model.model_refactored.GETNucleotideMotifAdaptor
  cfg:
    motif_scanner:
      num_motif: 128
      include_reverse_complement: false
      bidirectional_except_ctcf: false
      motif_prior: false
      learnable: true
      has_bias: true
    region_embed:
      num_regions: 10
      num_features: 283
      embed_dim: 768
    atac_attention:
      motif_dim: 128 # 637 motifs + 2 ctcf
      pool_method: "sum"
    loss:
      components:
        motif:
          _target_: torch.nn.MSELoss
          reduction: "mean"
      weights:
        motif: 1
    metrics:
      components:
        motif: ["pearson", "spearman", "r2"]
