zarr_dirs:
  - "vijay_hematopoiesis_dense.zarr"
leave_out_celltypes: "Mono.vijay_hematopoiesis.Young2_BMMC.1024"
leave_out_chromosomes: null
random_shift_peak: null
peak_name: "peaks_q0.01_tissue_open_exp"
dataset_size: 4096
additional_peak_columns:
  ["Expression_positive", "Expression_negative", "aTPM", "TSS"]
