zarr_dirs:
  - "encode_hg38atac_dense.zarr"
keep_celltypes: "k562.encode_hg38atac.ENCFF257HEE.max"
leave_out_celltypes: null
leave_out_chromosomes: "chr2,chr3,chr4,chr5,chr6,chr7,chr8,chr9,chr10,chr12,chr13,chr14,chr15,chr16,chr17,chr18,chr19,chr20,chr21,chr22,chrX"
peak_name: "peaks_q0.05_tissue_open_exp"
dataset_size: 8192
eval_dataset_size: 512
additional_peak_columns:
  ["Expression_positive", "Expression_negative", "aTPM", "TSS"]
center_expand_target: 0
n_peaks_lower_bound: 1
n_peaks_upper_bound: 200
negative_peak_name: null
negative_peak_ratio: 0
random_shift_peak: 0
max_peak_length: 5000
peak_count_filter: 10
use_insulation: False
preload_count: 10
pin_mem: True
n_packs: 1
padding: 0
mask_ratio: 0
insulation_subsample_ratio: 1
hic_path: null #/home/xf2217/Projects/encode_hg38atac/raw/ENCFF621AIY.hic