zarr_dirs:
  - "htan_gbm_dense.zarr"
keep_celltypes: "Tumor.htan_gbm.C3L-03405_CPT0224600013_snATAC_GBM_Tumor.4096"
leave_out_celltypes: null
leave_out_chromosomes: null
peak_name: "fetal_gbm_peaks_open_exp"
dataset_size: 40960
eval_dataset_size: 512
additional_peak_columns: ['Expression_positive', 'Expression_negative', 'aTPM', 'TSS']
center_expand_target: 0
n_peaks_lower_bound: 1
n_peaks_upper_bound: 900
negative_peak_name: null
negative_peak_ratio: 0
random_shift_peak: 0
max_peak_length: 5000
use_insulation: False
preload_count: 10
pin_mem: True
n_packs: 1
padding: 0
mask_ratio: 0
insulation_subsample_ratio: 1
reference_region_motif:
  data: 'fetal_gbm_peak_motif_v1.hg38.zarr'
  refdata: 'fetal_union_peak_motif_v1.hg38.zarr'
  count_filter: 0
  motif_scaler: 1

