defaults:
  - base_config
  - model/GETChrombpNet@_here_
  - finetune/lightning@finetune
  - dataset/finetune_k562@dataset
  - machine/pc
  - _self_

assembly: "hg38"
dataset:
  center_expand_target: 2114
  n_peaks_lower_bound: 0
  n_peaks_upper_bound: 1
  peak_count_filter: 100
  random_shift_peak: 100

machine:
  batch_size: 32
  num_workers: 32

training:
  save_ckpt_freq: 5
  epochs: 100
  warmup_epochs: 1
  accumulate_grad_batches: 1
  clip_grad: null
  use_fp16: true

optimizer:
  lr: 0.0001
  min_lr: 0.0001
  weight_decay: 0.05
  opt: "adamw"
  opt_eps: 1e-8
  opt_betas: [0.9, 0.95]

wandb:
  project_name: "k562_chrombpnet"
  run_name: "k562_chrombpnet_dnase.ENCFF257HEE"

finetune:
  checkpoint: null
  patterns_to_freeze: []
