defaults:
  - base_config
  - model/GETChrombpNet@_here_
  - dataset@dataset
  - machine/pc_chrombpnet
  - _self_

task:
  layer_names: []
  test_mode: "perturb"
  gene_list:
    - "PPIF"
  mutations: "/home/xf2217/Projects/get_data/prepared_data.tsv"

dataset_name: finetune_thp1
assembly: "hg38"
dataset:
  center_expand_target: 2114
  n_peaks_lower_bound: 1
  n_peaks_upper_bound: 1
  peak_name: "peaks_chrombpnet_filtered_open"
  negative_peak_name: "peaks_negative_tissue_open_exp"
  negative_peak_ratio: 0.1

training:
  save_ckpt_freq: 1
  epochs: 100
  warmup_epochs: 1
  accumulate_grad_batches: 1
  clip_grad: null
  use_fp16: false

optimizer:
  lr: 0.00005
  min_lr: 0.0001
  weight_decay: 0.05
  opt: "adamw"
  opt_eps: 1e-8
  opt_betas: [0.9, 0.95]

wandb:
  project_name: "chrombpnet"
  run_name: "thp1"

finetune:
  checkpoint: null
  model_prefix: "model."
  patterns_to_freeze: []
