data_set: "Expression_Finetune_k562.Chr4&14"
eval_data_set: "Expression_Finetune_k562.Chr4&14.Eval"
data_path: "/home/xf2217/Projects/get_data/"
batch_size: 2
num_workers: 2
n_peaks_lower_bound: 5
n_peaks_upper_bound: 10
max_peak_length: 5000
center_expand_target: 500
use_insulation: false
preload_count: 10
random_shift_peak: 10
pin_mem: true
peak_name: "peaks_p0.01_tissue_open_exp"
negative_peak_name: null
n_packs: 1
leave_out_celltypes: "k562"
leave_out_chromosomes: "chr4,chr14"
dataset_size: 4096
additional_peak_columns: ['Expression_positive', 'Expression_negative', 'aTPM', 'TSS']
padding: 0
mask_ratio: 0.5
insulation_subsample_ratio: 1
negative_peak_ratio: 0
peak_inactivation: null
non_redundant: false
filter_by_min_depth: false
hic_path: null