dataset_configs:
  pretrain:
    data_set: "Pretrain"
    eval_data_set: null
    zarr_dirs:
      - "shendure_fetal_dense.zarr"
      - "encode_hg38atac_dense.zarr"
      - "vijay_hematopoiesis_dense.zarr"
      - "htan_gbm_dense.zarr"
      - "bingren_adult_dense.zarr"
    leave_out_celltypes: null
    additional_peak_columns: null

  pretrain_gbm_eval:
    data_set: "Pretrain.GBM_eval"
    eval_data_set: null
    zarr_dirs:
      - "htan_gbm_dense.zarr"
    leave_out_celltypes: null
    additional_peak_columns: null
    dataset_size: 4096

  finetune_k562:
    data_set: "Expression_Finetune_k562.Chr4&14"
    eval_data_set: "Expression_Finetune_k562.Chr4&14.Eval"
    zarr_dirs:
      - "encode_hg38atac_dense.zarr"
    leave_out_celltypes: null
    leave_out_chromosomes: "chr4,chr14"
    random_shift_peak: null
    peak_name: "peaks_p0.05_tissue_open_exp"
    mutations: "/home/xf2217/Projects/get_data/prepared_data.tsv"
    dataset_size: 4096

  finetune_thp1:
    data_set: "Expression_Finetune_thp1.Chr4&14"
    eval_data_set: "Expression_Finetune_thp1.Chr4&14.Eval"
    zarr_dirs:
      - "encode_hg38atac_dense.zarr"
    leave_out_celltypes: "THP1"
    leave_out_chromosomes: null
    random_shift_peak: null
    peak_name: "peaks_p0.05_tissue_open"
    dataset_size: 4096
    additional_peak_columns: ["aTPM"]
  # Add more dataset configurations as needed

  finetune_monocyte:
    data_set: "Expression_Finetune_monocyte.Chr4&14"
    eval_data_set: "Expression_Finetune_monocyte.Chr4&14.Eval"
    zarr_dirs:
      - "vijay_hematopoiesis_dense.zarr"
    leave_out_celltypes: "Mono.vijay_hematopoiesis.Young2_BMMC.1024"
    leave_out_chromosomes: null
    random_shift_peak: null
    peak_name: "peaks_q0.01_tissue_open_exp"
    dataset_size: 4096
    additional_peak_columns:
      ["Expression_positive", "Expression_negative", "aTPM", "TSS"]
