defaults:
  - base_region_config
  - model/GETRegionFinetune@_here_
  - machine/pc_chrombpnet
  - _self_

dataset_name: eval_fetal_region
assembly: "hg38"

dataset:
    root: '/home/xf2217/Projects/new_finetune_data_all'
    metadata_path: 'cell_type_align.txt'
    num_region_per_sample: 900
    transform: null
    data_type: 'fetal'
    leave_out_celltypes: 'Erythroblasts'
    leave_out_chromosomes: 'chr1,chr2,chr3,chr4,chr5'
    use_natac: false
    sampling_step: 50

training:
  save_ckpt_freq: 1
  epochs: 100
  warmup_epochs: 1
  accumulate_grad_batches: 1
  clip_grad: null
  use_fp16: false

optimizer:
  lr: 0.00005
  min_lr: 0.0001
  weight_decay: 0.05
  opt: "adamw"
  opt_eps: 1e-8
  opt_betas: [0.9, 0.95]

wandb:
  project_name: "debug"
  run_name: "debug"

finetune:
  checkpoint: null
  model_prefix: "model."
  patterns_to_freeze: []
