defaults:
  - base_ref_region_config
  - model/GETNucleotideMotifAdaptor@_here_
  - machine/pc
  - finetune/v1_finetune@finetune
  - dataset/k562_nucleotide_adaptor@dataset
  - _self_

assembly: "hg38"

task:
  layer_names: []
  test_mode: "interpret"

training:
  save_ckpt_freq: 1
  epochs: 100
  warmup_epochs: 1
  accumulate_grad_batches: 1
  clip_grad: null
  use_fp16: false

dataset:
  quantitative_atac: true
  sampling_step: 10
  mask_ratio: 0

optimizer:
  lr: 0.001
  min_lr: 0.000001
  weight_decay: 0.05
  opt: "adamw"
  opt_eps: 1e-8
  opt_betas: [0.9, 0.999]

wandb:
  project_name: "nucleotide_motif_adaptor"
  run_name: "NTToQATAC"

finetune:
  pretrain_checkpoint: false
  strict: false
  use_lora: false
  checkpoint: /home/xf2217/Projects/get_checkpoints/Astrocytes/checkpoint-best.pth
  patterns_to_freeze: []
  model_key: 'model'


eval_tss: true
log_image: false
