defaults:
  - base_ref_region_config
  - model/GETRegionFinetune@_here_
  - machine/manitou
  - dataset/gbm_ref_eval@dataset
  - _self_

assembly: "hg38"

task:
  layer_names: []
  test_mode: "inference"
  gene_list: genes.txt
  mutations: regions.txt

training:
  save_ckpt_freq: 1
  epochs: 100
  warmup_epochs: 1
  accumulate_grad_batches: 1
  clip_grad: null
  use_fp16: false

dataset:
  quantitative_atac: true
  sampling_step: 100
  mask_ratio: 0

optimizer:
  lr: 0.0001
  min_lr: 0.000001
  weight_decay: 0.05
  opt: "adamw"
  opt_eps: 1e-8
  opt_betas: [0.9, 0.999]

wandb:
  project_name: "GETRegionFinetune_gbm"
  run_name: "debug"

finetune:
  pretrain_checkpoint: false
  strict: true
  use_lora: false
  checkpoint: "/home/xf2217/Projects/get_checkpoints/Astrocytes/checkpoint-best.pth"
  model_prefix: "model."
  patterns_to_freeze: []

eval_tss: true
log_image: false
