defaults:
  - base_region_config
  - model/GETRegionFinetune@_here_
  - machine/pc_region_v1
  - _self_

assembly: "hg38"

dataset:
    root: ${machine.data_path}
    metadata_path: 'cell_type_align.txt'
    num_region_per_sample: 900
    transform: null
    data_type: 'fetal'
    leave_out_celltypes: 'Astrocytes'
    leave_out_chromosomes: 'chr11'
    quantitative_atac: false
    sampling_step: 5

training:
  save_ckpt_freq: 1
  epochs: 100
  warmup_epochs: 1
  accumulate_grad_batches: 1
  clip_grad: null
  use_fp16: false

optimizer:
  lr: 0.0001
  min_lr: 0.0001
  weight_decay: 0.05
  opt: "adamw"
  opt_eps: 1e-8
  opt_betas: [0.9, 0.999]

wandb:
  project_name: "GETRegionFinetuneV1"
  run_name: "Astrocyte"

finetune:
  pretrain_checkpoint: false
  checkpoint: "/home/xf2217/Projects/get_checkpoints/Astrocytes_natac/checkpoint-best.pth"
  model_prefix: "model."
  patterns_to_freeze: []

eval_tss: true
