defaults:
  - base_config
  - model/GETFinetune@_here_
  - dataset@dataset
  - machine/pc
  - _self_

dataset_name: finetune_k562
assembly: "hg38"

task:
  layer_names: ["atac_attention"]
  test_mode: "perturb_interpret"
  gene_list: 
    - "PPIF"

training:
  save_ckpt_freq: 10
  epochs: 2
  warmup_epochs: 1
  accumulate_grad_batches: 1
  clip_grad: null
  use_fp16: true

optimizer:
  lr: 0.0001
  min_lr: 0.0001
  weight_decay: 0.05
  opt: "adamw"
  opt_eps: 1e-8
  opt_betas: [0.9, 0.95]

wandb:
  project_name: "debug_finetune"
  run_name: "experiment_1"

finetune:
  checkpoint: "/home/xf2217/Projects/get_checkpoints/Expression_Finetune_K562_HSC.Chr4_14.conv50.atac_loss.from_pretrain_399.nofreeze.use_insulation.nodepth.gap50.shift10.R100L1000.augmented.20240225.best.pth"
  model_prefix: "model."
  patterns_to_freeze: []

