defaults:
  - base_ref_region_config
  - model/GETRegionFinetunePositional@_here_
  - machine/manitou
  - dataset/k562_ref_eval@dataset
  - _self_

assembly: "hg38"

task:
  layer_names: []
  test_mode: "interpret"
  gene_list: /burg/pmg/users/xf2217/CRISPR_comparison/genes.txt
  mutations: /burg/pmg/users/xf2217/CRISPR_comparison/regions.txt

training:
  save_ckpt_freq: 1
  epochs: 100
  warmup_epochs: 1
  accumulate_grad_batches: 1
  clip_grad: null
  use_fp16: false

dataset:
  quantitative_atac: true
  sampling_step: 100
  mask_ratio: 0

optimizer:
  lr: 0.0001
  min_lr: 0.000001
  weight_decay: 0.05
  opt: "adamw"
  opt_eps: 1e-8
  opt_betas: [0.9, 0.999]

run:
  project_name: "GETRegionFinetuneLoRA_k562"
  run_name: "Positional-only"

finetune:
  pretrain_checkpoint: false
  strict: true
  use_lora: true
  checkpoint: "/home/xf2217/Projects/get_checkpoints/Astrocytes/checkpoint-best.pth"
  patterns_to_freeze: []

eval_tss: true
log_image: false
