# config/config.yaml
defaults:
  - model: pretrain/getpretrain_maxnorm
  - wandb_project_name: "getpretrain"
  - wandb_run_name: "getpretrain_maxnorm"
  - log_dir: "/pmglocal/xf2217/logs/${wandb_project_name}/${wandb_run_name}/"

# Other common configurations
log_freq: 10
loggers:
  - type: wandb
    wandb:
      project_name: ${wandb_project_name}
      run_name: ${wandb_run_name}

  - type: local
    local:
      log_dir: ${log_dir}
