defaults:
  - base_ref_region_config
  - model/GETRegionPretrain@_here_
  - machine/pc
  - dataset/tfatlas_eval@dataset
  - _self_

assembly: "hg38"

training:
  save_ckpt_freq: 1
  epochs: 100
  warmup_epochs: 1
  accumulate_grad_batches: 1
  clip_grad: null
  use_fp16: false

dataset:
  quantitative_atac: true
  sampling_step: 100
  mask_ratio: 0.5

optimizer:
  lr: 0.0001
  min_lr: 0.000001
  weight_decay: 0.05
  opt: "adamw"
  opt_eps: 1e-8
  opt_betas: [0.9, 0.999]

run:
  project_name: "GETRegionPretrain"
  run_name: "TFAtlas"

finetune:
  pretrain_checkpoint: true
  strict: false
  checkpoint: "/burg/pmg/users/xf2217/get_checkpoints/output_e800_r900_mask0.5_adult_watac/checkpoint-799.pth"
  patterns_to_freeze: []

eval_tss: false
log_image: true
