defaults:
  - base_region_config
  - model/GETRegionFinetuneATAC@_here_
  - machine/pc_region_v2
  - _self_

assembly: "hg38"
model:
  cfg:
    num_regions: 200
dataset:
    root: ${machine.data_path}
    metadata_path: 'data/cell_type_pretrain_human_bingren_shendure_apr2023.txt'
    num_region_per_sample: 200
    transform: null
    data_type: 'k562'
    leave_out_celltypes: 'k562_count_10'
    leave_out_chromosomes: "chr11"
    quantitative_atac: true
    sampling_step: 50
    mask_ratio: 0.5

training:
  save_ckpt_freq: 1
  epochs: 100
  warmup_epochs: 1
  accumulate_grad_batches: 1
  clip_grad: null
  use_fp16: false

optimizer:
  lr: 0.001
  min_lr: 0.000001
  weight_decay: 0.05
  opt: "adamw"
  opt_eps: 1e-8
  opt_betas: [0.9, 0.999]

wandb:
  project_name: "GETRegionFinetuneATAC"
  run_name: "k562_count_10"

finetune:
  checkpoint: 'GETRegionPretrain/jd2g64mg/checkpoints/best.ckpt'
  model_prefix: "model."
  patterns_to_freeze: []
